create table if not exists public.entries (
  id bigint generated by default as identity primary key,
  label text not null,
  detail text not null,
  created_at timestamptz not null default now()
);

alter table public.entries enable row level security;

drop policy if exists "Anyone can read entries" on public.entries;
create policy "Anyone can read entries"
  on public.entries
  for select
  to anon
  using (true);

drop policy if exists "Anyone can create entries" on public.entries;
create policy "Anyone can create entries"
  on public.entries
  for insert
  to anon
  with check (true);
